version: '3.7'
services:
  api-test:
    build:
      context: .
      dockerfile: docker/app/development/Dockerfile
    volumes:
    - .:/var/www/html
    environment:
    - COMPOSER_MEMORY_LIMIT=-1
    depends_on:
    - database-test

  database-test:
    image: postgres:15.1-alpine
    ports:
    - 54320:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}

networks:
  default:
    name: linkextractor
